### ISSUE TITLE
Temp directory as the 3rd fallback for TLDs cache file

### ISSUE THREAD

**Issue by lipoja** [lipoja/URLExtract#25]
As suggested by @keyz182 in https://github.com/lipoja/URLExtract/pull/24#issuecomment-427651263 it would be nice to have fallback to temp directory when we are trying to download TLDs to cache file.

**Comment by lipoja** [comment]
For my use case its OK to have it as second option - replacing home. Maybe its better place than user's home. Its not that persistent (as you mentioned) but it is fine by me.

**Comment by jayvdb** [comment]
Why not keep the files in a cache directory according to https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

There are a few packages which provide cross platform-ish xdg support

https://pypi.org/search/?q=xdg

The most commonly used is https://pypi.org/project/appdirs/

**Comment by lipoja** [comment]
Thank you for pointing it out. 
I used appdirs for getting the user's cache dir.

**Comment by roniemartinez** [comment]
@lipoja 

Trying to reopen an old ticket since there is a permission error on this implementation.

This line throws permission error when there is not enough privilege (tested in Linux):
https://github.com/lipoja/URLExtract/blob/master/urlextract/cachefile.py#L113

Write permission should be checked first before creating the cache directory.

Thanks!

**Comment by lipoja** [comment]
This reopened issue should be fixed in v0.14.0.
