### ISSUE TITLE
Email addresses are detected as URLs

### ISSUE THREAD

**Issue by impredicative** [lipoja/URLExtract#37]
Individual email addresses are detected as URLs. For example:

* abuse@facebook.com
* test@test.com

Email addresses should not be classified as URLs. Thanks.

----
For anyone else who runs into this issue, for now I'm using an oversimplified regex to approximately filter out such values:

    urls = [url for url in urls if not re.fullmatch(r'[^@]+@[^@]+\.[^@]+', url)]

**Comment by garrit-schroeder** [comment]
Thanks for the workaround!

+1

**Comment by lipoja** [comment]
Hi,
but I think that the mail is valid URL at least according to [RFC1738](https://tools.ietf.org/html/rfc1738). Where URL consists of `<scheme>://<user>:<password>@<host>:<port>/<url-path>` Some or all of the parts `"<user>:<password>@"`, `":<password>"`, `":<port>"`, and `"/<url-path>"` may be excluded. 

Because you can have `ftp://login@server.com` as a valid URL therefore I removed '@' from defaults stop characters. And now it returning emails within found URLs. 

But if you want to collect at least the host from the URL. For example "test@test.com" -> "test.com" you can set the urlextract like this:
But if you are sure that you don't want to parse URLs with <user>:<password>@ the easiest way how to do it is:
```python
from urlextract import URLExtract

extractor = URLExtract()
left_stop_chars = extractor.get_stop_chars_left() | {'@'}  # adding '@' as left stop character
extractor.set_stop_chars_left(left_stop_chars)

print(extractor.find_urls('test@test.com')) 
```
But with this settings you will never know it returned URL was part of email or not.

Do you agree and can we close this issue? Or should we discuss it more?

**Comment by impredicative** [comment]
I acknowledge that `ftp://login@server.com` is a valid URL.

I don't see how `login@server.com` is valid because most URLs are typically interpreted by other applications as having a scheme of `https` or `http`, not `ftp`. In theory there could be an application that interprets it has having the `ftp` scheme, but the odds of it are low.

I suspect that at least 9 out of 10 users who see an email address being returned as a URL are not going to be happy with it. As such, I think it has to be decided whether `urlextract` should be more accurate or more useful; apparently the two are at odds.

Maybe the one who needs it detected can remove `@` from the left stop characters instead.

**Comment by iamtodor** [comment]
I decided to do email extraction right before URL extraction: 
`re.sub(r'[\w.-]+@[\w.-]+\.?\w+', ' isemail ', remove_url)`,

**Comment by lipoja** [comment]
I am still thinking about this issue and I will take @impredicative's comment/suggestion, that I would not extract emails (URL with `@` sign) when there is no scheme specified. I would try to make it to next release.

**Comment by lipoja** [comment]
Extraction of email addresses is disabled by default since version 0.11. When there is no schema before URI with user info the URL is not returned. 

Extraction of email can be turned on by setting:
`extractor = URLExtract(extract_email=True)`
or 
`extractor.extract_email = True`

**Comment by impredicative** [comment]
Thanks. I confirm the change via this test:

```python
>>> from urlextract import URLExtract
>>> URLExtract.get_version()
'0.11'
>>> extractor = URLExtract()
>>> extractor.find_urls('test@test.com')
[]
```
