### ISSUE TITLE
Incomplete URL extracted

### ISSUE THREAD

**Issue by impredicative** [lipoja/URLExtract#39]
An incomplete URL was extracted from a larger string. Here is the minimal code:

```python
>>> import urlextract
>>> urlextract.__version__
'0.10'
>>> url_extractor = urlextract.URLExtract()
>>> input_url = "https://www.semanticscholar.org/paper/When-You-Eat-Matters%3A-60-Years-of-Franz-Halberg's-Cornelissen/3c57ee642835494a8b46f3ff4799f746d3a4607f"
>>> url_extractor.find_urls(input_url)
['https://www.semanticscholar.org/paper/When-You-Eat-Matters%3A-60-Years-of-Franz-Halberg']
```
I would like for the full URL to have been extracted instead. I don't see why it should stop after `'`. Thanks.

**Comment by lipoja** [comment]
Tricky question,
there has to be add more logic for the parsing to fix this issue. Because right now there is no check if the text was given in single quotes or not. And I was wrong when I set `'` as stop character. 

I was assuming that `'` can appear only when there is code like: 
`<a src='http://example.com/'>example</a>`

**Comment by lipoja** [comment]
This issue might be solved. It was easy fix at the end, I hope it did not introduce other problems. But my current test cases passed :]

**Comment by impredicative** [comment]
That's nice but I find it's weird to close an issue without issuing a release. I can't really conveniently verify anything if there is no new release. I request that a release be made as soon as an issue is fixed.
