### ISSUE TITLE
list of url exception

### ISSUE THREAD

**Issue by iamtodor** [lipoja/URLExtract#40]
Hello! Is there a way to make some list of URL exceptions? For example, I consider `youtube.com/channel/UC22n-g_flDuGDvUgFPkAgIw` as URL, but `asp.net` I don't want to be detected as a URL. Is it possible to achieve?

**Comment by lipoja** [comment]
Hi,
well not right now with use of urlextract. The easiest way is to remove it from the list of URLs that is extracted by yourself. Because it is exactly what I would have to implement in the urlextract. Check every extracted URL and see if it is `asp.net` or if is sub-domain of that. 

Different request would be not detect `.net` or `.com`. For this case I would suggest to give urlextract you own (modified) list of TLDs.

Am I correct that you want to just remove `asp.net` from the list?

**Comment by iamtodor** [comment]
@lipoja yes, I just implemented this item checking by my own. 
If I understand you right not exactly: I don't want `asp.net` to be detected as url, therefore, I want to leave it in my text, but any other urls remove from the text.

**Comment by lipoja** [comment]
Hi,
if I implement this list of exceptions does it should be exact match of URL? 
For example if you give me ["asp.net"] as exception:
only "asp.net" would be ignored but "http://asp.net/" would be returned?

Or should it be based on domain both string from example would be ignored (not extracted).

Could you help me define its behavior?

**Comment by iamtodor** [comment]
Hello,
I think you are right: I would expect everything starts with `http` to be considered as URL. So despite I have `exceptions=['aps.net']` the following values 'http://asp.net/', 'https://asp.net/', 'www.asp.net/'
are treated as URL

**Comment by lipoja** [comment]
And what about when you have "asp.net" as exception and there is "blog.asp.net" on the input ... should this domain be printed (extracted - not ignored)? 
Based on you example above I would assume that it would be ignored, because asp.net is on the exception list. Same behavior as in your example with www.asp.net. Both www. and blog. are sub-domains.

**Comment by iamtodor** [comment]
Yes, exception list - exact match, otherwise (substrings) are being detected as URL. Do you think it's a bad idea?

**Comment by lipoja** [comment]
I vote for exact match on hostname/domain. Example:
Excluded URL: 
- example.com

What will be blocked/not extracted:
- http://example.com
- example.com
- http://example.com:1234/url/path/file.html?query=something#hash

What won't be blocked/will be extracted (returned by find_urls):
- http://any.subdomain.example.com:1234/path/file.html?query=something#hashtag
- whatever.example.com
- www.example.com (because it is subdomain and hostname is not exact match)

**Comment by lipoja** [comment]
OK, I am going to implement the exact match on hostname.

**Comment by lipoja** [comment]
urlextract now (from v0.14.0) supports ignore URL list. 
URLs on this ignore lists are matched using exact match as mentioned above.
