### ISSUE TITLE
&amp; problem

### ISSUE THREAD

**Issue by kristiansvenssonsweco** [lipoja/URLExtract#49]
This URL is getting chopped of:
https://secure.webforum.com/fut/projects/documents?dfRefID=64282&amp;ProjectID=48830

to this after running it through find_urls:
https://secure.webforum.com/fut/projects/documents?dfRefID=64282&amp

Is this by design? Meaning that I should always unescape any strings before running URLExtract?

**Comment by lipoja** [comment]
Thank you for reporting this issue. Unfortunately yes, it is there by design. It is extracting URL checking character on left and on right side of TLD if they match with any of "stop characters". And ';' is one of them. If you want to exclude ';' you can do it by setting your own set of stop characters via [get_stop_chars_right()](https://urlextract.readthedocs.io/en/latest/urlextract.html#urlextract.URLExtract.get_stop_chars_right) and [set_stop_chars_right()](https://urlextract.readthedocs.io/en/latest/urlextract.html#urlextract.URLExtract.set_stop_chars_right) methods.

Note: get the set of characters,  remove the semicolon from it and then set the new set back.

Will this solve your problem? I think that I can not make it work by default for every use case that exists. This is just a tool and you should know what data you are processing and customize the urlextract accordingly. Meaning setting the "stop characters" to fit your needs.

**Comment by kristiansvenssonsweco** [comment]
Thanks!
I solved it by using 
`html.unescape(str)`

However you methods would probably work just as good!
